database:
  host: mysql
  port: 3306
  user: root
  password: root
  databaseName: inu_2
client:
  auth:
    session:
      cookieName: inu_backyard
      prefix: $
      secret: secret
      maxAge: 604800 # 7 days in second unit
    turnstile:
      secretKey: 2x0000000000000000000000000000000AA
  cors:
    AllowOrigins:
      - "http://localhost:3000"
      - "https://inugardenview.vercel.app"
