version: "3.8"

services:
  app:
    container_name: inu_server
    image: ghcr.io/jokpoon/inu-backyard:latest
    ports:
      - 3001:3001
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - caddy_net

  mysql:
    image: mysql:8.1.0
    container_name: inu_mysql
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always     # Automatically restart the container on failure or system reboot
    environment:
      MYSQL_ROOT_PASSWORD: root  # Set the root password
      MYSQL_DATABASE: inu_backyard  
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 3s
      retries: 10
    networks:
      - caddy_net

  phpmyadmin:
    container_name: inu_phpmyadmin
    image: phpmyadmin:5.2.1
    ports:
      - 8080:8080
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true

volumes:
  mysql_data:
