services:
  app:
    container_name: inu_server
    image: ghcr.io/jokpoon/inu-backyard:latest
    ports:
      - 3001:3001
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - caddy_net

  mysql:
    image: mysql:8.1.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    expose:
      - 3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1s
      timeout: 3s
      retries: 30
    networks:
      - caddy_net

  phpmyadmin:
    image: phpmyadmin:5.2.1
    expose:
      - 8080
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true

volumes:
  mysql_data:
